customhost = "employee.cukpezuuwkup.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee"
custombucket = "mys3projectbucket"
customregion = "US East (N. Virginia) us-east-1"
